---
project_name: waftf

release:
  github:
    owner: signalsciences
    name: waf-testing-framework

builds:
  - binary: waftf
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/
    ldflags: -s -w -X main.waftfversion={{.Version}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yml
      - payloads/**/*

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - Merge pull request
      - Merge branch
